modify: 优化逻辑，确保一定编译webdav模块

diff --git a/docker/nginx-webdav b/docker/nginx-webdav
--- a/docker/nginx-webdav
+++ b/docker/nginx-webdav
@@ -27,69 +27,56 @@ ENV PACKAGES=" \
 ENV REVISION ${NGINX_VERSION}-${PKG_RELEASE}
 ENV PKGOSSCHECKSUM 3a4e869eded0c71e92f522e94edffea7fbfb5e78886ea7e484342fa2e028c62099a67d08860c249bf93776da97b924225e0d849dbb4697b298afe5421d7d6fea
 # 添加 module-webdav 到 BUILDTARGET 中
-ENV BUILDTARGET "module-geoip module-image-filter module-njs module-xslt"
-
-
+ENV BUILDTARGET "module-geoip module-image-filter module-njs module-xslt module-webdav"
 
 RUN set -x \
     && apkArch="$(cat /etc/apk/arch)" \
     && nginxPackages="$PACKAGES" \
-# install prerequisites for public key and pkg-oss checks
-    && apk add --no-cache --virtual .checksum-deps \
-        openssl \
-    && case "$apkArch" in \
-        x86_64|aarch64) \
-# arches officially built by upstream
-            apk add -X "$PACKAGEREPO/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $nginxPackages \
-            ;; \
-        *) \
-# we're on an architecture upstream doesn't officially build for
-# let's build binaries from the published packaging sources
-            set -x \
-            && tempDir="$(mktemp -d)" \
-            && chown nobody:nobody $tempDir \
-            && apk add --no-cache --virtual .build-deps \
-                gcc \
-                libc-dev \
-                make \
-                openssl-dev \
-                pcre2-dev \
-                zlib-dev \
-                linux-headers \
-                libxslt-dev \
-                gd-dev \
-                geoip-dev \
-                libedit-dev \
-                bash \
-                alpine-sdk \
-                findutils \
-                curl \
-            # 下载并解压 WebDAV 扩展模块
-            && curl -f -L -O $NGINX_DAV_EXT_MODULE_URL \
-            && tar xzvf v${NGINX_DAV_EXT_MODULE_VERSION}.tar.gz \
-            && echo "下载并解压WebDAV： ${NGINX_DAV_EXT_MODULE_URL}" \
-            && su nobody -s /bin/sh -c " \
-                export HOME=${tempDir} \
-                && cd ${tempDir} \
-                && curl -f -L -O https://github.com/nginx/pkg-oss/archive/${REVISION}.tar.gz \
-                && PKGOSSCHECKSUM=\"$PKGOSSCHECKSUM *${REVISION}.tar.gz\" \
-                && if [ \"\$(openssl sha512 -r ${REVISION}.tar.gz)\" = \"\$PKGOSSCHECKSUM\" ]; then \
-                    echo \"pkg-oss tarball checksum verification succeeded!\"; \
-                else \
-                    echo \"pkg-oss tarball checksum verification failed!\"; \
-                    exit 1; \
-                fi \
-                && tar xzvf ${REVISION}.tar.gz \
-                && cd pkg-oss-${REVISION} \
-                && cd alpine \
-                && ./configure --add-module=../../nginx-dav-ext-module-${NGINX_DAV_EXT_MODULE_VERSION} \
-                && make $BUILDTARGET || { echo "Make failed"; exit 1; } \
-                && apk index --allow-untrusted -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
-                && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
-                " \
-            && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
-            && apk del --no-network .build-deps \
-            && apk add -X ${tempDir}/packages/alpine/ --no-cache $nginxPackages \
+    && apk add --no-cache --virtual .checksum-deps openssl \
+    && tempDir="$(mktemp -d)" \
+    && chown nobody:nobody $tempDir \
+    && apk add --no-cache --virtual .build-deps \
+        gcc \
+        libc-dev \
+        make \
+        openssl-dev \
+        pcre2-dev \
+        zlib-dev \
+        linux-headers \
+        libxslt-dev \
+        gd-dev \
+        geoip-dev \
+        libedit-dev \
+        bash \
+        alpine-sdk \
+        findutils \
+        curl \
+    # 下载并解压 WebDAV 扩展模块
+    && curl -f -L -O $NGINX_DAV_EXT_MODULE_URL \
+    && tar xzvf v${NGINX_DAV_EXT_MODULE_VERSION}.tar.gz \
+    && echo "下载并解压WebDAV： ${NGINX_DAV_EXT_MODULE_URL}" \
+    && su nobody -s /bin/sh -c " \
+        export HOME=${tempDir} \
+        && cd ${tempDir} \
+        && curl -f -L -O https://github.com/nginx/pkg-oss/archive/${REVISION}.tar.gz \
+        && PKGOSSCHECKSUM=\"$PKGOSSCHECKSUM *${REVISION}.tar.gz\" \
+        && if [ \"\$(openssl sha512 -r ${REVISION}.tar.gz)\" = \"\$PKGOSSCHECKSUM\" ]; then \
+            echo \"pkg-oss tarball checksum verification succeeded!\"; \
+        else \
+            echo \"pkg-oss tarball checksum verification failed!\"; \
+            exit 1; \
+        fi \
+        && tar xzvf ${REVISION}.tar.gz \
+        && cd pkg-oss-${REVISION} \
+        && cd alpine \
+        && ./configure --add-module=../../nginx-dav-ext-module-${NGINX_DAV_EXT_MODULE_VERSION} \
+        && make $BUILDTARGET || { echo \"Make failed\"; exit 1; } \
+        && apk index --allow-untrusted -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
+        && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
+        " \
+    && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
+    && apk del --no-network .build-deps \
+    && apk add -X ${tempDir}/packages/alpine/ --no-cache $nginxPackages \
             ;; \
     esac \
 # remove checksum deps
